---
- name: Create Web Service
  hosts: webservers
  become: yes

  roles:
    - { role: common, tags: common }
    - { role: users, tags: users }
    - { role: sshd, tags: sshd }
    - { role: apache, tags: apache }
    - { role: mysql, tags: mysql }
