---
- name: sshd / Change SSH port
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^Port"
    insertafter: "^#Port"
    line: "Port {{ port }}"

- name: sshd / Disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    insertafter: "^#PasswordAuthentication"
    line: "PasswordAuthentication no"

- name: sshd / Disallow challenge & response authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^ChallengeResponseAuthentication"
    insertafter: "^#ChallengeResponseAuthentication"
    line: "ChallengeResponseAuthentication no"

- name: sshd / Disallow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    insertafter: "^#PermitRootLogin"
    line: "PermitRootLogin no"

- name: sshd / Restart
  systemd:
    name: sshd
    state: restarted

- name: "sshd / Open firewalld port ({{ port }})"
  firewalld:
    port: "{{ port }}/tcp"
    permanent: true
    state: enabled
    immediate: true

- name: sshd / Close firewalld service (ssh)
  firewalld:
    service: ssh
    permanent: true
    state: disabled
    immediate: true

- name: sshd / Close firewalld port (22)
  firewalld:
    port: 22/tcp
    permanent: true
    state: disabled
    immediate: true
